### PR TITLE
Make case_id mandatory

### PR DESCRIPTION
**Pull request by LJBabbage**
### What is the context of this PR?
For census case_id was made optional, this PR reverts it back to mandatory for business surveys

### How to review 
Make sure everything still works, that case_id is now mandatory and tests have been changed. Also check that condition statements and defaults involving case_id have all been updated and nothing has been missed

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by MebinAbraham — COMMENTED** [review]
Can now be bound to the logger in `session.login`.

**Comment by LJBabbage** [comment]
> Can now be bound to the logger in `session.login`.

Completely forgot about that. Another card :laughing ?

**Review by MebinAbraham — COMMENTED** [review]
Case ID can be accessed directly instead of calling `.get("case_id")` since we know it is mandatory. It removes the ambiguity of whether it might not exist at some point in the request journey.

**Comment by LJBabbage** [comment]
> Case ID can be accessed directly instead of calling `.get("case_id")` since we know it is mandatory. It removes the ambiguity of whether it might not exist at some point in the request journey.

We oddly do that for a number of mandatory fields (submission, flush and authenticator) which we might want to do the same.

**Comment by JamesGardiner** [comment]
> > Case ID can be accessed directly instead of calling `.get("case_id")` since we know it is mandatory. It removes the ambiguity of whether it might not exist at some point in the request journey.
> 
> We oddly do that for a number of mandatory fields (submission, flush and authenticator) which we might want to do the same.

Also, there is a mixture of using `.get` and `[]` notation throughout Runner. If we are going to change it we should make it consistent everywhere, though that should potentially be a different PR

**Review by JamesGardiner — APPROVED** [review]
Changes look good - I'd like to update all the instances of where `case_id` is accessed using `.get` as it implies that it's optional, when it's not. This may need an update to our runner style guide to some degree, to say that optional keys should be accessed using `.get` whilst mandatory keys should be  square bracket notation, but happy to move that to another PR if that is the group consensus?

**Review by MebinAbraham — APPROVED** [review]

**Pull request merged**
