### PR TITLE
Update python packages to resolve warnings

### PR DESCRIPTION
**Pull request by berroar**
### What is the context of this PR?
Updates dependencies to resolve the issues listed here: https://github.com/ONSdigital/eq-questionnaire-runner/security/dependabot

Added fixes for tests relating to the dependency updates.

Pinned mypy as upgrading caused some existing type hints to fail the check, will raise a separate card to address this.

### How to review
Check nothing is broken, run a benchmark against this branch.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by berroar** [comment]
[Update Runner Python Packages](https://trello.com/c/aJXZPIUY/5949-update-runner-python-packages)

**Comment by berroar** [comment]
[Update Runner Python Packages](https://trello.com/c/aJXZPIUY/5949-update-runner-python-packages)

**Comment by berroar** [comment]
[Update Runner Python Packages](https://trello.com/c/aJXZPIUY/5949-update-runner-python-packages)

**Review by petechd — APPROVED** [review]
Looks good, tested both in test and staging and main is very similar to this branch. Main is the first run in this graph below (staging).

performance_graph (7)

**Review by katie-gardner — APPROVED** [review]
Changes and comments make sense 👍 My pipeline benchmark is acting up.. but I've run one locally and got a similar result, looking good
performance_graph

**Pull request merged**
