### PR TITLE
Bug: Cross-section when rule dependencies not working as expected fix

### PR DESCRIPTION
**Pull request by creativeappdevamit**
### What is the context of this PR?
[Bug: Cross-section when rule dependencies not working as expected](Bug: Cross-section when rule dependencies not working as expected)

### How to review

With the current main branch 

- Launch phm-0001 schema 
- Answer questions until you get to the age question
- Answer No to are you aged 16 or above.
- You will eventually get to a question that says Have you ever smoked cigarettes regularly?
This question should not have been in the path as it was dependent on the age.

With fix branch 

- Launch phm-0001 schema 
- Answer questions until you get to the age question
- Answer No to are you aged 16 or above.
- You will not get to a question that says Have you ever smoked cigarettes regularly?

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by MebinAbraham — COMMENTED** [review]
As discussed, will need functional tests for this.

**Comment by creativeappdevamit** [comment]
> As discussed, will need functional tests for this.

Added the functional tests now.

**Review by Yuyuutsu — APPROVED** [review]
Tested and it works as expected. 👍  LGTM

**Review by ONS-Guilhem-Forey — APPROVED** [review]

**Comment by Hajara-I** [comment]
Tested and it all looks good to me

**Pull request merged**
