### PR TITLE
Schemas v3.53.0

### PR DESCRIPTION
**Pull request by MebinAbraham**
### What is the context of this PR?
Latest schema release https://github.com/ONSdigital/eq-questionnaire-schemas/releases/tag/v3.53.0

### How to review
Ensure the correct version is loaded when running `make build`

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by berroar — APPROVED** [review]

**Review by kylelawsonAND — APPROVED** [review]
All good, fetches schema v3.53.0 👍

**Review by Yuyuutsu — DISMISSED** [review]
```
      "id": "sectionquestionnaire-introduction",
      "title": "Introduction",
      "show_on_hub": false,
      "groups": [
        {
          "id": "groupquestionnaire-introduction",
```
I dont think this affects anything but should they be seperated like `group-questionnaire-introduction`. DID NOT MEAN TO APPROVE

**Review by Yuyuutsu — APPROVED** [review]
Schema loads as expected 👍

**Comment by MebinAbraham** [comment]
> ```
>       "id": "sectionquestionnaire-introduction",
>       "title": "Introduction",
>       "show_on_hub": false,
>       "groups": [
>         {
>           "id": "groupquestionnaire-introduction",
> ```
> 
> I dont think this affects anything, but should they be separated like `group-questionnaire-introduction`?

They generate ids etc, but this is down to author.

**Pull request merged**
