### PR TITLE
Update sign out logic to check for the existence of session data

### PR DESCRIPTION
**Pull request by MebinAbraham**
### What is the context of this PR?
Updates the sign out endpoints logic also check for the existence of the session data to prevent the error: `"AttributeError: 'NoneType' object has no attribute 'language_code'"`

No tests have been added as we could not recreate this issue from a user's perspective. The implications of this has been understood and agreed with Andrew, James and Mark.

### How to review 
- Ensure sign out behaviour still works as expected and this change has not adverse effects.
- Submit a census themed survey, then delete your eq-session object from Datastore and ensure that when you click `Exit` then you are redirected to the census website.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by ajmaddaford — APPROVED** [review]
Tested in a GCP environment 👍

**Review by JamesGardiner — APPROVED** [review]

**Review by pricem14pc — APPROVED** [review]
Successfully tested locally

**Review by ajmaddaford — APPROVED** [review]

**Review by JamesGardiner — APPROVED** [review]

**Review by pricem14pc — APPROVED** [review]
Good spot!

**Review by LJBabbage — APPROVED** [review]
Testing on GCP works

**Pull request merged**
