### PR TITLE
Fix mobile ni logo

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Mobile version of the NI finance logo was set as the main NI logo. This will fix this and add a test

### How to review 
Check `test_theme_northenireland` schema for both small screens and full size screens and see that it is the correct logo and that the logo changes size

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by rmccar** [comment]
[Update DS to v60 (2 SP)](https://trello.com/c/KX8jjdAp/5469-update-ds-to-v60-2-sp)

**Review by petechd — APPROVED** [review]

**Comment by MebinAbraham** [comment]
The DS v60 upgrade has broken the language toggle in the header (No longer displayed). Can you take a look before closing the card off. Will need to add a test to ensure it doesn't happen again.

**Comment by rmccar** [comment]
> The DS v60 upgrade has broken the language toggle in the header (No longer displayed). Can you take a look before closing the card off. Will need to add a test to ensure it doesn't happen again.

Just looking at the test_language schema and the language toggle appears for me

**Review by Yuyuutsu — APPROVED** [review]

**Review by berroar — APPROVED** [review]

**Comment by rmccar** [comment]
[Release: v5.0.1](https://trello.com/c/ZYs9ongu/5489-release-v501)

**Pull request merged**
