### PR TITLE
Update error message content for 500 errors

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
New content of 500 error pages to make them less generic. Updated existing tests, one of them wasn't testing what expected (had to change the theme to "social" instead of "default/business". New translations generated for the new strings.

### How to review
Existing tests expanded so just run these. Visually compare/check the changes in the 500 error template while in the app.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Update error message content for 500 errors (1 SP)](https://trello.com/c/n7il1xS8/5884-update-error-message-content-for-500-errors-1-sp)

**Review by berroar — APPROVED** [review]
LGTM, tested 👍  Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?

**Comment by MebinAbraham** [comment]
> LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?

We should test ass scenarios. We can just delete the cookie, to test unknown theme.

**Comment by petechd** [comment]
> > LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?
> 
> We should test all scenarios. We can just delete the cookie, to test unknown theme.

@MebinAbraham I think we discussed it before, when we worked on the 500 error pages before, I think if we delete the cookie we end up on one of the 400 pages so it is impossible to test it in integration test?

**Comment by MebinAbraham** [comment]
> > > LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?
> > 
> > 
> > We should test all scenarios. We can just delete the cookie, to test unknown theme.
> 
> @MebinAbraham I think we discussed it before, when we worked on the 500 error pages or cookies, I think if we delete the cookie we end up on one of the 400 pages so it is impossible to test it in integration test?

I should have been clearer. Delete the `theme` property of the cookies, not the entire cookie. Try that.

**Comment by MebinAbraham** [comment]
> > > > > LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?
> > > > 
> > > > 
> > > > We should test all scenarios. We can just delete the cookie, to test unknown theme.
> > > 
> > > 
> > > @MebinAbraham I think we discussed it before, when we worked on the 500 error pages or cookies, I think if we delete the cookie we end up on one of the 400 pages so it is impossible to test it in integration test?
> > 
> > 
> > I should have been clearer. Delete the `theme` property of the cookie, not the entire cookie. Try that.
> 
> Yeah, we tried this last time, we still are on the business themed 500 when the Exception happens (if we delete the theme in cookie midway). If we try launching with unknown theme we don't get to 500 page, only 401. We had a serious problem replicating this in integration tests last time. I've just tried different ways of getting rid of the theme in these tests and cannot force it to end up on the unknown theme 500.

Have you tried patching?. You could patch the `get_survey_type` method.

**Comment by petechd** [comment]
> > > > > > LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?
> > > > > 
> > > > > 
> > > > > We should test all scenarios. We can just delete the cookie, to test unknown theme.
> > > > 
> > > > 
> > > > @MebinAbraham I think we discussed it before, when we worked on the 500 error pages or cookies, I think if we delete the cookie we end up on one of the 400 pages so it is impossible to test it in integration test?
> > > 
> > > 
> > > I should have been clearer. Delete the `theme` property of the cookie, not the entire cookie. Try that.
> > 
> > 
> > Yeah, we tried this last time, we still are on the business themed 500 when the Exception happens (if we delete the theme in cookie midway). If we try launching with unknown theme we don't get to 500 page, only 401. We had a serious problem replicating this in integration tests last time. I've just tried different ways of getting rid of the theme in these tests and cannot force it to end up on the unknown theme 500.
> 
> Have you tried patching?. You could patch the `get_survey_type` method.

I patched that, we end up with 401 error instead of 500.

**Comment by MebinAbraham** [comment]
Test Slack

**Comment by MebinAbraham** [comment]
@Chudziak, Piotr  test

**Review by rmccar — APPROVED** [review]

**Comment by MebinAbraham** [comment]
> > > > > > > LGTM, tested 👍 Obviously we have tests for business and social but not the journey when we don't know the theme, but not sure that is able to be easily tested?
> > > > > > 
> > > > > > 
> > > > > > We should test all scenarios. We can just delete the cookie, to test unknown theme.
> > > > > 
> > > > > 
> > > > > @MebinAbraham I think we discussed it before, when we worked on the 500 error pages or cookies, I think if we delete the cookie we end up on one of the 400 pages so it is impossible to test it in integration test?
> > > > 
> > > > 
> > > > I should have been clearer. Delete the `theme` property of the cookie, not the entire cookie. Try that.
> > > 
> > > 
> > > Yeah, we tried this last time, we still are on the business themed 500 when the Exception happens (if we delete the theme in cookie midway). If we try launching with unknown theme we don't get to 500 page, only 401. We had a serious problem replicating this in integration tests last time. I've just tried different ways of getting rid of the theme in these tests and cannot force it to end up on the unknown theme 500.
> > 
> > 
> > Have you tried patching?. You could patch the `get_survey_type` method.
> 
> I patched that, we end up with 401 error instead of 500.

As discussed, have added test for the unknown survey type scenario.

**Review by berroar — APPROVED** [review]

**Review by rmccar — APPROVED** [review]

**Pull request merged**
