### PR TITLE
Fix dynamic answers functional test

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
Some changes had to be in introduced to the "dynamic answers based on list" tests to make it pass in current circumstances. Added refactoring plus extra checks to make it less flaky when using the new chromedriver version, user journeys are untouched, mainly refactoring for readability and to reduce repetition but also new elements in `generate_pages`.

### How to review
See if you are happy with the changes, I've tested many variants of this fix and tried to minimise the amount of extra code but this seems to be minimum we need for it to pass.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Bug: Functional tests with a dropdown can fail if the component doesn't load](https://trello.com/c/VaPuP630/5745-bug-functional-tests-with-a-dropdown-can-fail-if-the-component-doesnt-load)

**Comment by kylelawsonAND** [comment]
Screenshot 2023-06-05 at 11 06 56
Screenshot 2023-06-05 at 11 06 42
Screenshot 2023-06-05 at 11 04 38
Screenshot 2023-06-05 at 11 04 09
Screenshot 2023-06-05 at 11 03 49


I have all the attached func tests failing - the test affected by your change passed fine it seems.
Ran `pipenv install --dev` and `yarn install`, `yarn generate_pages` and `make build` prior to running the tests - anything I missed there?

**Comment by petechd** [comment]
> Screenshot 2023-06-05 at 11 06 56 Screenshot 2023-06-05 at 11 06 42 Screenshot 2023-06-05 at 11 04 38 Screenshot 2023-06-05 at 11 04 09 Screenshot 2023-06-05 at 11 03 49
> 
> I have all the attached func tests failing - the test affected by your change passed fine it seems. Ran `pipenv install --dev` and `yarn install`, `yarn generate_pages` and `make build` prior to running the tests - anything I missed there?

@kylelawsonAND must be old design system version or just rebuild the templates or even (most probable thing) restart runner, sometimes you have old version running eg. from before changing your branch.

**Review by Yuyuutsu — APPROVED** [review]
Changes look good to me 👍

**Review by Yuyuutsu — COMMENTED** [review]
Did notice github actions is using chromedriver 114 while locally its 113 for me. But not sure if its relevant here

**Comment by petechd** [comment]
> Did notice github actions is using chromedriver 114 while locally its 113 for me. But not sure if its relevant here

Or maybe it was version 114 of chrome browser? I have similar setup: chrome 114 and chromedriver 113..

**Comment by Yuyuutsu** [comment]
> > Did notice github actions is using chromedriver 114 while locally its 113 for me. But not sure if its relevant here
> 
> Or was it version 114 of chrome browser? I have similar setup: chrome 114 and chromedriver 113..

Oh thats what it is. My chrome browser is 113 while GA is 114. My bad 😅

**Comment by petechd** [comment]
> > > Did notice github actions is using chromedriver 114 while locally its 113 for me. But not sure if its relevant here
> > 
> > 
> > Or was it version 114 of chrome browser? I have similar setup: chrome 114 and chromedriver 113..
> 
> Oh thats what it is. My chrome browser is 113 while GA is 114. My bad 😅

You might need to update your chrome to keep functional tests happy..

**Pull request merged**
