### PR TITLE
Fix dates allowing 2 digit years

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This fixes the year validation so 2/3 digit years are not allowed anymore in forms.

### How to review 
Tests added and existing one refactored to support this change.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Bug: Dates allowing 2 digit years](https://trello.com/c/Mp3ta2a2/5522-bug-dates-allowing-2-digit-years)

**Comment by Yuyuutsu** [comment]
My tests are failing but my local runner has been pretty weird recently, so I will try again tomorrow.

**Review by rmccar — APPROVED** [review]

**Comment by berroar** [comment]
Do we need a better error message as slightly ambiguous from a user perspective:
Screenshot 2023-01-03 at 13 14 46

**Comment by petechd** [comment]
> Do we need a better error message as slightly ambiguous from a user perspective:
> 
New error message added that is specific about the year format, I've checked the wording with Donna and Oscar.

**Review by rmccar — APPROVED** [review]
New error message looks good to me as long as its signed off by content

**Comment by petechd** [comment]
> New error message looks good to me as long as its signed off by content

It's been looked at and approved by Donna and Oscar.

**Comment by petechd** [comment]
Oscar spoke to Jon from DS and the validation error message is slightly different now than what is on the card, but it's been approved.

**Review by berroar — APPROVED** [review]

**Pull request merged**
