### PR TITLE
Use list component for errors

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Using the list component for lists in error list panels fixes a bug where a list of one error is numbered.

image

Also fixes some code formatting in thank-you.html

Is dependant on #835 being merged first

### How to review 
- Test using `test_durations` schema
- Leave all mandatory fields blank and submit, see the error list is numbered
- Leave ons mandatory field blank and submit, see the error list is not numbered

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by rmccar** [comment]
[Error list panel bug](https://trello.com/c/2LmW7n9W/5253-error-list-panel-bug)

**Comment by petechd** [comment]
Best if we test this, something like:
```js

  it("Given the test_durations survey is selected when multiple mandatory durations are missing a numbered errors are shown", () => {
    $(DurationPage.mandatoryYearYears()).setValue(1);
    $(DurationPage.submit()).click();

    expect($("body").getHTML()).to.contain("error-link-1").to.contain("error-link-2");
  });
```

in `tests/functional/spec/durations.spec.js`, not sure if we should use `("body").getHTML()` tho.

**Comment by petechd** [comment]
Best if we test this, something like:
```js

  it("Given the test_durations survey is selected when multiple mandatory durations are missing a numbered errors are shown", () => {
    $(DurationPage.mandatoryYearYears()).setValue(1);
    $(DurationPage.submit()).click();

    expect($("body").getHTML()).to.contain("error-link-1").to.contain("error-link-2");
  });
```

in `tests/functional/spec/durations.spec.js`, not sure if we should use `("body").getHTML()` tho.

**Comment by rmccar** [comment]
> ```js
> it("Given the test_durations survey is selected when multiple mandatory durations are missing a numbered errors are shown", () => {
>     $(DurationPage.mandatoryYearYears()).setValue(1);
>     $(DurationPage.submit()).click();
> 
>     expect($("body").getHTML()).to.contain('<ol class="ons-list" data-qa="error-list">');
>   });
> ```

Yeah makes sense but wouldn't we want to use the error_messages spec instead? But yeah Id probably use a selector instead of `("body").getHTML()`

**Comment by rmccar** [comment]
Duplicate comment deleted

**Review by berroar — COMMENTED** [review]
Looks good 👍, just needs a test as @petechd mentioned

**Comment by MebinAbraham** [comment]
As briefly discussed in tech, we should avoid arbitrary selector where we can `'<ol class="ons-list" data-qa="error-list">'`. It would be good to use sector via page object generated by generate pages.

**Review by petechd — APPROVED** [review]

**Review by berroar — APPROVED** [review]

**Pull request merged**
