### PR TITLE
Load schemas in runner and expose endpoint

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
This PR will make changes to allow loading schemas in Runner build for the new schema folder structure and expose schemas in schemas endpoint.

### How to review 
- schemas endpoint works
- `make load-schemas` works as expected

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by rmccar** [comment]
[Load schemas in Runner build and expose in schemas endpoint (2 SP)](https://trello.com/c/rxXnVcTg/4961-load-schemas-in-runner-build-and-expose-in-schemas-endpoint-2-sp)

**Comment by rmccar** [comment]
[Present schemas in launcher to be separated by subfolders](https://trello.com/c/4WekpmXn/4986-present-schemas-in-launcher-to-be-separated-by-subfolders)

**Comment by MebinAbraham** [comment]
https://github.com/ONSdigital/eq-questionnaire-runner/pull/731 includes these changes?

**Comment by rmccar** [comment]
> #731 includes these changes?

Yeah as we wanted to get these changes in as quickly as possible I split this out from #731, while we finished the work on that PR. As the changes in this PR are dependent on this I included them in both because I thought this could be reviewed and merged before we finished the other one. But as we have finished the work on all of it now I suppose I can delete this PR and just have people review the other one

**Pull request closed without merging**
