### PR TITLE
Add and resize tick icons to templates

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This adds and resizes tick icon in multiple templates. Change is described on this [trello card](https://trello.com/c/LKHelDnS).

### How to review 
Manually go through census to check if templates have changed.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Add tick icons to IR success panels and increase size of tick on thank you page panel (xs)](https://trello.com/c/LKHelDnS/4253-add-tick-icons-to-ir-success-panels-and-increase-size-of-tick-on-thank-you-page-panel-xs)

**Review by LJBabbage — CHANGES_REQUESTED** [review]
I am confused, as I was expected, svg-icon--l, and svg-icon--xl so l and xl in the iconSize according to the card, but I am seeing s and m.

**Comment by petechd** [comment]
> I am confused, as I was expected, svg-icon--l, and svg-icon--xl in the UI so l and xl in the iconSize according to the card, but I am seeing s and m.

I was thinking I will match heading size, which in all cases  is a class: `u-mb-s` or `u-mb-m` where `mb` stands for margins and `m` and `s` at the end stands for heading font size?

**Review by JamesGardiner — APPROVED** [review]

**Review by LJBabbage — CHANGES_REQUESTED** [review]
This is all good, however I have just asked Rich to take a quick look, because the panels we are using are inconsistent. Some are u-mb-s and others u-mb-m, I reckon they should all be the same

**Comment by petechd** [comment]
> This is all good, however I have just asked Rich to take a quick look, because the panels we are using are inconsistent. Some are u-mb-s and others u-mb-m, I reckon they should all be the same

I can always change them in files that I modified in this PR if devs want that.

**Review by LJBabbage — APPROVED** [review]
Talked to Rich, they are going to review this, but this PR is good to go

**Pull request merged**
