### PR TITLE
Update packages and version to Python 3.12

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This updates project's Python to version 3.12 and updates some of the dev libraries since the poetry lock required regeneration as well. As a result some new flake8 config and some test changes had to be made.

### How to review
Run benchmark and test all the places where Python got updated.

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by ons-eq-team** [comment]
**Benchmark Results**<br /><br />Percentile Averages:<br />50th: 84ms<br />90th: 153ms<br />95th: 259ms<br />99th: 842ms<br />99.9th: 1667ms<br />GETs (99th): 1249ms<br />POSTs (99th): 371ms<br /><br />PDF: 2800ms<br />Session: 47000ms<br /><br />Total Requests: 66,244<br />Total Failures: 0<br />Error Percentage: 0.0%<br />

**Comment by berroar** [comment]
> **Benchmark Results**Percentile Averages:50th: 84ms90th: 153ms95th: 259ms99th: 842ms99.9th: 1667msGETs (99th): 1249msPOSTs (99th): 371msPDF: 2800msSession: 47000msTotal Requests: 66,244Total Failures: 0Error Percentage: 0.0%

The stats here are not great, and although they have been up and down recently in benchmark i think it is worth running some more tests to assess whether there are some performance implications here.

**Comment by ons-eq-team** [comment]
**Benchmark Results**<br /><br />Percentile Averages:<br />50th: 83ms<br />90th: 146ms<br />95th: 236ms<br />99th: 931ms<br />99.9th: 1805ms<br />GETs (99th): 1450ms<br />POSTs (99th): 332ms<br /><br />PDF: 3100ms<br />Session: 60000ms<br /><br />Total Requests: 65,980<br />Total Failures: 1<br />Error Percentage: 0.0%<br />

**Review by Yuyuutsu — COMMENTED** [review]
Do we need to do a Performance investigation in benchmark?

**Comment by ons-eq-team** [comment]
**Benchmark Results**<br /><br />Percentile Averages:<br />50th: 85ms<br />90th: 217ms<br />95th: 784ms<br />99th: 1300ms<br />99.9th: 2601ms<br />GETs (99th): 1765ms<br />POSTs (99th): 762ms<br /><br />PDF: 4000ms<br />Session: 52000ms<br /><br />Total Requests: 63,620<br />Total Failures: 2<br />Error Percentage: 0.0%<br />

**Review by Yuyuutsu — APPROVED** [review]
Changes look good, and benchmark results seem similar to the results you have run.

**Review by rmccar — APPROVED** [review]

**Comment by ons-eq-team** [comment]
**Benchmark Results**<br /><br />Percentile Averages:<br />50th: 105ms<br />90th: 325ms<br />95th: 499ms<br />99th: 1019ms<br />99.9th: 1979ms<br />GETs (99th): 1166ms<br />POSTs (99th): 849ms<br /><br />PDF: 7100ms<br />Session: 6700ms<br /><br />Total Requests: 63,095<br />Total Failures: 0<br />Error Percentage: 0.0%<br />

**Pull request merged**
