### PR TITLE
Update static content translations

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Update static content translations

### How to review
Test the translations are working in runner

### Checklist
* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by rmccar** [comment]
[Update Runner's static content translations (1 SP)](https://trello.com/c/h7dqKnJQ/5674-update-runners-static-content-translations-1-sp)

**Comment by rmccar** [comment]
[Alert in Slack when a Runner 403 (1 SP)](https://trello.com/c/95wxRAIC/5667-alert-in-slack-when-a-runner-403-1-sp)

**Comment by berroar** [comment]
The changes look ok but noticed there is an issue in the file on line 860: msgstr[2] "Mae %(num)s broblem gyda'ch adborth". It uses `adborth` i.e feedback rather than `ateb`/`answer`

**Review by berroar — APPROVED** [review]

**Comment by katie-gardner** [comment]
Have checked the po file matches the ticket except for the line highlighted by Rhys, make translate is working, and the translations are showing up properly in runner including the new ones, so looks OK to me 👍

**Review by katie-gardner — APPROVED** [review]

**Pull request merged**
