### PR TITLE
Bug Fix logger values not being bound to logs

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
Since vars are not binding to logger, Structlog needs to be pinned to older version, along with flask-babel, black and pylint which cause some issues when unpinned after dependencies update. This pr only temporarily pins them so the logs issue is fixed.

### How to review 
Check if runner is behaving as expected after dependencies update.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Bug: Runner logger binds are not being bound](https://trello.com/c/cKQnfkrq/5555-bug-runner-logger-binds-are-not-being-bound)

**Review by berroar — APPROVED** [review]
Looks like the missing logs are back 👍

**Comment by MebinAbraham** [comment]
Can you update the PR title to what the change actually does.

**Review by ONS-Guilhem-Forey — APPROVED** [review]
Tested locally with updated py version and packages, and seems to be working for me too 👍

**Pull request merged**
