### PR TITLE
Add icons to Thank you page

### PR DESCRIPTION
**Pull request by berroar**
### What is the context of this PR?
The green tick and padlock icons were missing from the `census-thank-you` page, this PR updates the template so that they appear.

### How to review 
Use any of the `test_thank_you` schemas and check the missing icons now appear on the page.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by berroar** [comment]
[Missing icons on thank you page](https://trello.com/c/5Fpap0Pk/4134-missing-icons-on-thank-you-page)

**Review by MebinAbraham — COMMENTED** [review]
They should be on all variations?. I.e non census theme etc

**Comment by berroar** [comment]
> They should be on all variations?. I.e non census theme etc

I've added the green tick to the non census page now, but not sure if the padlock needs to be there? Doesn't really match the text

**Review by MebinAbraham — APPROVED** [review]

**Comment by MebinAbraham** [comment]
> > They should be on all variations?. I.e non census theme etc
> 
> I've added the green tick to the non census page now, but not sure if the padlock needs to be there? Doesn't really match the text

Might be worth checking with Donna.

**Review by JamesGardiner — APPROVED** [review]

**Comment by berroar** [comment]
Confirmed with @donnap573 that there is no need for the padlock icon on the non census thank you page.

**Pull request merged**
