### PR TITLE
Update footer copyright parameters

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This removes `link`, `url` and `target` in the copyright declaration in the footer. Words 'terms and conditions' are now part of the same `text` string. Change is described on [this Trello](https://trello.com/c/jkRlGJ4x).

### How to review 
Check in census schemas if footer has the full `Use of address data is subject to the terms and conditions` text now.

### Checklist

* [x] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by petechd** [comment]
[Update footer copyright parameters - DS breaking change in v31.4.3 (xs)](https://trello.com/c/jkRlGJ4x/4529-update-footer-copyright-parameters-ds-breaking-change-in-v3143-xs)

**Review by LJBabbage — CHANGES_REQUESTED** [review]
I seem to have a double full stop now

**Comment by petechd** [comment]
> I seem to have a double full stop now

Did you load latest design system templates or `make build`?

**Review by berroar — APPROVED** [review]

**Review by LJBabbage — APPROVED** [review]
I just pulled the branch and ran it. Didn't expect a design system update to remove a full stop

**Pull request merged**
