### PR TITLE
Update template content for Calculated Summary & Grand Calculated Summary

### PR DESCRIPTION
**Pull request by liamtoozer**
### What is the context of this PR?
Tweaks button wording and removes blue banner help from screen to match updated content design. 

Note: This update caused a few other areas to translations message file to change

### How to review
Load `test_calculated_summary` schema, navigate to the calculated summary screen and ensure that the rendered page matches the spec shown in the Trello ticket

### Checklist
* [x] New static content marked up for translation

### CODE REVIEW

**Comment by liamtoozer** [comment]
[Content changes - calculated summary screen (1 SP)](https://trello.com/c/NiCNJEet/5799-content-changes-calculated-summary-screen-1-sp)

**Review by berroar — CHANGES_REQUESTED** [review]
Since we were able to update this and looks like nothing broke/no tests needed to change, it is probably worth adding a test somewhere that checks this text 👍

**Review by berroar — APPROVED** [review]

**Review by MebinAbraham — APPROVED** [review]
👍

**Comment by MebinAbraham** [comment]
Waiting for confirmation that Grand summary should have also been updated (I would assume so)

**Comment by MebinAbraham** [comment]
Confirmed both Calc and Grand Calc should be the same.

**Review by MebinAbraham — APPROVED** [review]

**Pull request merged**
