### PR TITLE
Update Chromedriver to 100.0.0

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
Update ChromeDriver to 100.

### How to review 
Make sure it passes all the checks.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by MebinAbraham** [comment]
Latest one is 101.

**Comment by petechd** [comment]
For yarn the latest is 100. https://yarnpkg.com/package/chromedriver

**Comment by petechd** [comment]
Yarn's latest is 100: https://yarnpkg.com/package/chromedriver.

**Comment by MebinAbraham** [comment]
> Yarn's latest is 100: [yarnpkg.com/package/chromedriver](https://yarnpkg.com/package/chromedriver).

Odd that it is working against 101 which is what we install (latest)

**Review by MebinAbraham — APPROVED** [review]

**Review by berroar — APPROVED** [review]

**Comment by petechd** [comment]
[Update chromedriver to 100.0.0](https://trello.com/c/uZAFZhDu/5274-update-chromedriver-to-10000)

**Pull request merged**
